# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:
.PHONY : .NOTPARALLEL

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/local/bin/cmake

# The command to remove a file.
RM = /opt/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/dghost/quake2vr

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/dghost/quake2vr

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/local/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	cd /Users/dghost/quake2vr && $(CMAKE_COMMAND) -E cmake_progress_start /Users/dghost/quake2vr/CMakeFiles /Users/dghost/quake2vr/game/CMakeFiles/progress.marks
	cd /Users/dghost/quake2vr && $(MAKE) -f CMakeFiles/Makefile2 game/all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/dghost/quake2vr/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /Users/dghost/quake2vr && $(MAKE) -f CMakeFiles/Makefile2 game/clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /Users/dghost/quake2vr && $(MAKE) -f CMakeFiles/Makefile2 game/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /Users/dghost/quake2vr && $(MAKE) -f CMakeFiles/Makefile2 game/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /Users/dghost/quake2vr && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
game/CMakeFiles/vrgamex86.dir/rule:
	cd /Users/dghost/quake2vr && $(MAKE) -f CMakeFiles/Makefile2 game/CMakeFiles/vrgamex86.dir/rule
.PHONY : game/CMakeFiles/vrgamex86.dir/rule

# Convenience name for target.
vrgamex86: game/CMakeFiles/vrgamex86.dir/rule
.PHONY : vrgamex86

# fast build rule for target.
vrgamex86/fast:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/build
.PHONY : vrgamex86/fast

__/qcommon/shared/m_flash.o: __/qcommon/shared/m_flash.c.o
.PHONY : __/qcommon/shared/m_flash.o

# target to build an object file
__/qcommon/shared/m_flash.c.o:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/__/qcommon/shared/m_flash.c.o
.PHONY : __/qcommon/shared/m_flash.c.o

__/qcommon/shared/m_flash.i: __/qcommon/shared/m_flash.c.i
.PHONY : __/qcommon/shared/m_flash.i

# target to preprocess a source file
__/qcommon/shared/m_flash.c.i:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/__/qcommon/shared/m_flash.c.i
.PHONY : __/qcommon/shared/m_flash.c.i

__/qcommon/shared/m_flash.s: __/qcommon/shared/m_flash.c.s
.PHONY : __/qcommon/shared/m_flash.s

# target to generate assembly for a file
__/qcommon/shared/m_flash.c.s:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/__/qcommon/shared/m_flash.c.s
.PHONY : __/qcommon/shared/m_flash.c.s

__/qcommon/shared/q_shared.o: __/qcommon/shared/q_shared.c.o
.PHONY : __/qcommon/shared/q_shared.o

# target to build an object file
__/qcommon/shared/q_shared.c.o:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/__/qcommon/shared/q_shared.c.o
.PHONY : __/qcommon/shared/q_shared.c.o

__/qcommon/shared/q_shared.i: __/qcommon/shared/q_shared.c.i
.PHONY : __/qcommon/shared/q_shared.i

# target to preprocess a source file
__/qcommon/shared/q_shared.c.i:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/__/qcommon/shared/q_shared.c.i
.PHONY : __/qcommon/shared/q_shared.c.i

__/qcommon/shared/q_shared.s: __/qcommon/shared/q_shared.c.s
.PHONY : __/qcommon/shared/q_shared.s

# target to generate assembly for a file
__/qcommon/shared/q_shared.c.s:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/__/qcommon/shared/q_shared.c.s
.PHONY : __/qcommon/shared/q_shared.c.s

acesrc/acebot_ai.o: acesrc/acebot_ai.c.o
.PHONY : acesrc/acebot_ai.o

# target to build an object file
acesrc/acebot_ai.c.o:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/acesrc/acebot_ai.c.o
.PHONY : acesrc/acebot_ai.c.o

acesrc/acebot_ai.i: acesrc/acebot_ai.c.i
.PHONY : acesrc/acebot_ai.i

# target to preprocess a source file
acesrc/acebot_ai.c.i:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/acesrc/acebot_ai.c.i
.PHONY : acesrc/acebot_ai.c.i

acesrc/acebot_ai.s: acesrc/acebot_ai.c.s
.PHONY : acesrc/acebot_ai.s

# target to generate assembly for a file
acesrc/acebot_ai.c.s:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/acesrc/acebot_ai.c.s
.PHONY : acesrc/acebot_ai.c.s

acesrc/acebot_cmds.o: acesrc/acebot_cmds.c.o
.PHONY : acesrc/acebot_cmds.o

# target to build an object file
acesrc/acebot_cmds.c.o:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/acesrc/acebot_cmds.c.o
.PHONY : acesrc/acebot_cmds.c.o

acesrc/acebot_cmds.i: acesrc/acebot_cmds.c.i
.PHONY : acesrc/acebot_cmds.i

# target to preprocess a source file
acesrc/acebot_cmds.c.i:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/acesrc/acebot_cmds.c.i
.PHONY : acesrc/acebot_cmds.c.i

acesrc/acebot_cmds.s: acesrc/acebot_cmds.c.s
.PHONY : acesrc/acebot_cmds.s

# target to generate assembly for a file
acesrc/acebot_cmds.c.s:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/acesrc/acebot_cmds.c.s
.PHONY : acesrc/acebot_cmds.c.s

acesrc/acebot_compress.o: acesrc/acebot_compress.c.o
.PHONY : acesrc/acebot_compress.o

# target to build an object file
acesrc/acebot_compress.c.o:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/acesrc/acebot_compress.c.o
.PHONY : acesrc/acebot_compress.c.o

acesrc/acebot_compress.i: acesrc/acebot_compress.c.i
.PHONY : acesrc/acebot_compress.i

# target to preprocess a source file
acesrc/acebot_compress.c.i:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/acesrc/acebot_compress.c.i
.PHONY : acesrc/acebot_compress.c.i

acesrc/acebot_compress.s: acesrc/acebot_compress.c.s
.PHONY : acesrc/acebot_compress.s

# target to generate assembly for a file
acesrc/acebot_compress.c.s:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/acesrc/acebot_compress.c.s
.PHONY : acesrc/acebot_compress.c.s

acesrc/acebot_items.o: acesrc/acebot_items.c.o
.PHONY : acesrc/acebot_items.o

# target to build an object file
acesrc/acebot_items.c.o:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/acesrc/acebot_items.c.o
.PHONY : acesrc/acebot_items.c.o

acesrc/acebot_items.i: acesrc/acebot_items.c.i
.PHONY : acesrc/acebot_items.i

# target to preprocess a source file
acesrc/acebot_items.c.i:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/acesrc/acebot_items.c.i
.PHONY : acesrc/acebot_items.c.i

acesrc/acebot_items.s: acesrc/acebot_items.c.s
.PHONY : acesrc/acebot_items.s

# target to generate assembly for a file
acesrc/acebot_items.c.s:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/acesrc/acebot_items.c.s
.PHONY : acesrc/acebot_items.c.s

acesrc/acebot_movement.o: acesrc/acebot_movement.c.o
.PHONY : acesrc/acebot_movement.o

# target to build an object file
acesrc/acebot_movement.c.o:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/acesrc/acebot_movement.c.o
.PHONY : acesrc/acebot_movement.c.o

acesrc/acebot_movement.i: acesrc/acebot_movement.c.i
.PHONY : acesrc/acebot_movement.i

# target to preprocess a source file
acesrc/acebot_movement.c.i:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/acesrc/acebot_movement.c.i
.PHONY : acesrc/acebot_movement.c.i

acesrc/acebot_movement.s: acesrc/acebot_movement.c.s
.PHONY : acesrc/acebot_movement.s

# target to generate assembly for a file
acesrc/acebot_movement.c.s:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/acesrc/acebot_movement.c.s
.PHONY : acesrc/acebot_movement.c.s

acesrc/acebot_nodes.o: acesrc/acebot_nodes.c.o
.PHONY : acesrc/acebot_nodes.o

# target to build an object file
acesrc/acebot_nodes.c.o:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/acesrc/acebot_nodes.c.o
.PHONY : acesrc/acebot_nodes.c.o

acesrc/acebot_nodes.i: acesrc/acebot_nodes.c.i
.PHONY : acesrc/acebot_nodes.i

# target to preprocess a source file
acesrc/acebot_nodes.c.i:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/acesrc/acebot_nodes.c.i
.PHONY : acesrc/acebot_nodes.c.i

acesrc/acebot_nodes.s: acesrc/acebot_nodes.c.s
.PHONY : acesrc/acebot_nodes.s

# target to generate assembly for a file
acesrc/acebot_nodes.c.s:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/acesrc/acebot_nodes.c.s
.PHONY : acesrc/acebot_nodes.c.s

acesrc/acebot_spawn.o: acesrc/acebot_spawn.c.o
.PHONY : acesrc/acebot_spawn.o

# target to build an object file
acesrc/acebot_spawn.c.o:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/acesrc/acebot_spawn.c.o
.PHONY : acesrc/acebot_spawn.c.o

acesrc/acebot_spawn.i: acesrc/acebot_spawn.c.i
.PHONY : acesrc/acebot_spawn.i

# target to preprocess a source file
acesrc/acebot_spawn.c.i:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/acesrc/acebot_spawn.c.i
.PHONY : acesrc/acebot_spawn.c.i

acesrc/acebot_spawn.s: acesrc/acebot_spawn.c.s
.PHONY : acesrc/acebot_spawn.s

# target to generate assembly for a file
acesrc/acebot_spawn.c.s:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/acesrc/acebot_spawn.c.s
.PHONY : acesrc/acebot_spawn.c.s

g_ai.o: g_ai.c.o
.PHONY : g_ai.o

# target to build an object file
g_ai.c.o:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/g_ai.c.o
.PHONY : g_ai.c.o

g_ai.i: g_ai.c.i
.PHONY : g_ai.i

# target to preprocess a source file
g_ai.c.i:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/g_ai.c.i
.PHONY : g_ai.c.i

g_ai.s: g_ai.c.s
.PHONY : g_ai.s

# target to generate assembly for a file
g_ai.c.s:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/g_ai.c.s
.PHONY : g_ai.c.s

g_camera.o: g_camera.c.o
.PHONY : g_camera.o

# target to build an object file
g_camera.c.o:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/g_camera.c.o
.PHONY : g_camera.c.o

g_camera.i: g_camera.c.i
.PHONY : g_camera.i

# target to preprocess a source file
g_camera.c.i:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/g_camera.c.i
.PHONY : g_camera.c.i

g_camera.s: g_camera.c.s
.PHONY : g_camera.s

# target to generate assembly for a file
g_camera.c.s:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/g_camera.c.s
.PHONY : g_camera.c.s

g_chase.o: g_chase.c.o
.PHONY : g_chase.o

# target to build an object file
g_chase.c.o:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/g_chase.c.o
.PHONY : g_chase.c.o

g_chase.i: g_chase.c.i
.PHONY : g_chase.i

# target to preprocess a source file
g_chase.c.i:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/g_chase.c.i
.PHONY : g_chase.c.i

g_chase.s: g_chase.c.s
.PHONY : g_chase.s

# target to generate assembly for a file
g_chase.c.s:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/g_chase.c.s
.PHONY : g_chase.c.s

g_cmds.o: g_cmds.c.o
.PHONY : g_cmds.o

# target to build an object file
g_cmds.c.o:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/g_cmds.c.o
.PHONY : g_cmds.c.o

g_cmds.i: g_cmds.c.i
.PHONY : g_cmds.i

# target to preprocess a source file
g_cmds.c.i:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/g_cmds.c.i
.PHONY : g_cmds.c.i

g_cmds.s: g_cmds.c.s
.PHONY : g_cmds.s

# target to generate assembly for a file
g_cmds.c.s:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/g_cmds.c.s
.PHONY : g_cmds.c.s

g_combat.o: g_combat.c.o
.PHONY : g_combat.o

# target to build an object file
g_combat.c.o:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/g_combat.c.o
.PHONY : g_combat.c.o

g_combat.i: g_combat.c.i
.PHONY : g_combat.i

# target to preprocess a source file
g_combat.c.i:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/g_combat.c.i
.PHONY : g_combat.c.i

g_combat.s: g_combat.c.s
.PHONY : g_combat.s

# target to generate assembly for a file
g_combat.c.s:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/g_combat.c.s
.PHONY : g_combat.c.s

g_crane.o: g_crane.c.o
.PHONY : g_crane.o

# target to build an object file
g_crane.c.o:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/g_crane.c.o
.PHONY : g_crane.c.o

g_crane.i: g_crane.c.i
.PHONY : g_crane.i

# target to preprocess a source file
g_crane.c.i:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/g_crane.c.i
.PHONY : g_crane.c.i

g_crane.s: g_crane.c.s
.PHONY : g_crane.s

# target to generate assembly for a file
g_crane.c.s:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/g_crane.c.s
.PHONY : g_crane.c.s

g_ctf.o: g_ctf.c.o
.PHONY : g_ctf.o

# target to build an object file
g_ctf.c.o:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/g_ctf.c.o
.PHONY : g_ctf.c.o

g_ctf.i: g_ctf.c.i
.PHONY : g_ctf.i

# target to preprocess a source file
g_ctf.c.i:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/g_ctf.c.i
.PHONY : g_ctf.c.i

g_ctf.s: g_ctf.c.s
.PHONY : g_ctf.s

# target to generate assembly for a file
g_ctf.c.s:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/g_ctf.c.s
.PHONY : g_ctf.c.s

g_fog.o: g_fog.c.o
.PHONY : g_fog.o

# target to build an object file
g_fog.c.o:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/g_fog.c.o
.PHONY : g_fog.c.o

g_fog.i: g_fog.c.i
.PHONY : g_fog.i

# target to preprocess a source file
g_fog.c.i:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/g_fog.c.i
.PHONY : g_fog.c.i

g_fog.s: g_fog.c.s
.PHONY : g_fog.s

# target to generate assembly for a file
g_fog.c.s:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/g_fog.c.s
.PHONY : g_fog.c.s

g_func.o: g_func.c.o
.PHONY : g_func.o

# target to build an object file
g_func.c.o:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/g_func.c.o
.PHONY : g_func.c.o

g_func.i: g_func.c.i
.PHONY : g_func.i

# target to preprocess a source file
g_func.c.i:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/g_func.c.i
.PHONY : g_func.c.i

g_func.s: g_func.c.s
.PHONY : g_func.s

# target to generate assembly for a file
g_func.c.s:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/g_func.c.s
.PHONY : g_func.c.s

g_items.o: g_items.c.o
.PHONY : g_items.o

# target to build an object file
g_items.c.o:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/g_items.c.o
.PHONY : g_items.c.o

g_items.i: g_items.c.i
.PHONY : g_items.i

# target to preprocess a source file
g_items.c.i:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/g_items.c.i
.PHONY : g_items.c.i

g_items.s: g_items.c.s
.PHONY : g_items.s

# target to generate assembly for a file
g_items.c.s:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/g_items.c.s
.PHONY : g_items.c.s

g_jetpack.o: g_jetpack.c.o
.PHONY : g_jetpack.o

# target to build an object file
g_jetpack.c.o:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/g_jetpack.c.o
.PHONY : g_jetpack.c.o

g_jetpack.i: g_jetpack.c.i
.PHONY : g_jetpack.i

# target to preprocess a source file
g_jetpack.c.i:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/g_jetpack.c.i
.PHONY : g_jetpack.c.i

g_jetpack.s: g_jetpack.c.s
.PHONY : g_jetpack.s

# target to generate assembly for a file
g_jetpack.c.s:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/g_jetpack.c.s
.PHONY : g_jetpack.c.s

g_lights.o: g_lights.c.o
.PHONY : g_lights.o

# target to build an object file
g_lights.c.o:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/g_lights.c.o
.PHONY : g_lights.c.o

g_lights.i: g_lights.c.i
.PHONY : g_lights.i

# target to preprocess a source file
g_lights.c.i:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/g_lights.c.i
.PHONY : g_lights.c.i

g_lights.s: g_lights.c.s
.PHONY : g_lights.s

# target to generate assembly for a file
g_lights.c.s:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/g_lights.c.s
.PHONY : g_lights.c.s

g_lock.o: g_lock.c.o
.PHONY : g_lock.o

# target to build an object file
g_lock.c.o:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/g_lock.c.o
.PHONY : g_lock.c.o

g_lock.i: g_lock.c.i
.PHONY : g_lock.i

# target to preprocess a source file
g_lock.c.i:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/g_lock.c.i
.PHONY : g_lock.c.i

g_lock.s: g_lock.c.s
.PHONY : g_lock.s

# target to generate assembly for a file
g_lock.c.s:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/g_lock.c.s
.PHONY : g_lock.c.s

g_main.o: g_main.c.o
.PHONY : g_main.o

# target to build an object file
g_main.c.o:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/g_main.c.o
.PHONY : g_main.c.o

g_main.i: g_main.c.i
.PHONY : g_main.i

# target to preprocess a source file
g_main.c.i:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/g_main.c.i
.PHONY : g_main.c.i

g_main.s: g_main.c.s
.PHONY : g_main.s

# target to generate assembly for a file
g_main.c.s:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/g_main.c.s
.PHONY : g_main.c.s

g_misc.o: g_misc.c.o
.PHONY : g_misc.o

# target to build an object file
g_misc.c.o:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/g_misc.c.o
.PHONY : g_misc.c.o

g_misc.i: g_misc.c.i
.PHONY : g_misc.i

# target to preprocess a source file
g_misc.c.i:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/g_misc.c.i
.PHONY : g_misc.c.i

g_misc.s: g_misc.c.s
.PHONY : g_misc.s

# target to generate assembly for a file
g_misc.c.s:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/g_misc.c.s
.PHONY : g_misc.c.s

g_model.o: g_model.c.o
.PHONY : g_model.o

# target to build an object file
g_model.c.o:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/g_model.c.o
.PHONY : g_model.c.o

g_model.i: g_model.c.i
.PHONY : g_model.i

# target to preprocess a source file
g_model.c.i:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/g_model.c.i
.PHONY : g_model.c.i

g_model.s: g_model.c.s
.PHONY : g_model.s

# target to generate assembly for a file
g_model.c.s:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/g_model.c.s
.PHONY : g_model.c.s

g_monster.o: g_monster.c.o
.PHONY : g_monster.o

# target to build an object file
g_monster.c.o:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/g_monster.c.o
.PHONY : g_monster.c.o

g_monster.i: g_monster.c.i
.PHONY : g_monster.i

# target to preprocess a source file
g_monster.c.i:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/g_monster.c.i
.PHONY : g_monster.c.i

g_monster.s: g_monster.c.s
.PHONY : g_monster.s

# target to generate assembly for a file
g_monster.c.s:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/g_monster.c.s
.PHONY : g_monster.c.s

g_moreai.o: g_moreai.c.o
.PHONY : g_moreai.o

# target to build an object file
g_moreai.c.o:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/g_moreai.c.o
.PHONY : g_moreai.c.o

g_moreai.i: g_moreai.c.i
.PHONY : g_moreai.i

# target to preprocess a source file
g_moreai.c.i:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/g_moreai.c.i
.PHONY : g_moreai.c.i

g_moreai.s: g_moreai.c.s
.PHONY : g_moreai.s

# target to generate assembly for a file
g_moreai.c.s:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/g_moreai.c.s
.PHONY : g_moreai.c.s

g_mtrain.o: g_mtrain.c.o
.PHONY : g_mtrain.o

# target to build an object file
g_mtrain.c.o:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/g_mtrain.c.o
.PHONY : g_mtrain.c.o

g_mtrain.i: g_mtrain.c.i
.PHONY : g_mtrain.i

# target to preprocess a source file
g_mtrain.c.i:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/g_mtrain.c.i
.PHONY : g_mtrain.c.i

g_mtrain.s: g_mtrain.c.s
.PHONY : g_mtrain.s

# target to generate assembly for a file
g_mtrain.c.s:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/g_mtrain.c.s
.PHONY : g_mtrain.c.s

g_patchplayermodels.o: g_patchplayermodels.c.o
.PHONY : g_patchplayermodels.o

# target to build an object file
g_patchplayermodels.c.o:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/g_patchplayermodels.c.o
.PHONY : g_patchplayermodels.c.o

g_patchplayermodels.i: g_patchplayermodels.c.i
.PHONY : g_patchplayermodels.i

# target to preprocess a source file
g_patchplayermodels.c.i:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/g_patchplayermodels.c.i
.PHONY : g_patchplayermodels.c.i

g_patchplayermodels.s: g_patchplayermodels.c.s
.PHONY : g_patchplayermodels.s

# target to generate assembly for a file
g_patchplayermodels.c.s:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/g_patchplayermodels.c.s
.PHONY : g_patchplayermodels.c.s

g_pendulum.o: g_pendulum.c.o
.PHONY : g_pendulum.o

# target to build an object file
g_pendulum.c.o:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/g_pendulum.c.o
.PHONY : g_pendulum.c.o

g_pendulum.i: g_pendulum.c.i
.PHONY : g_pendulum.i

# target to preprocess a source file
g_pendulum.c.i:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/g_pendulum.c.i
.PHONY : g_pendulum.c.i

g_pendulum.s: g_pendulum.c.s
.PHONY : g_pendulum.s

# target to generate assembly for a file
g_pendulum.c.s:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/g_pendulum.c.s
.PHONY : g_pendulum.c.s

g_phys.o: g_phys.c.o
.PHONY : g_phys.o

# target to build an object file
g_phys.c.o:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/g_phys.c.o
.PHONY : g_phys.c.o

g_phys.i: g_phys.c.i
.PHONY : g_phys.i

# target to preprocess a source file
g_phys.c.i:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/g_phys.c.i
.PHONY : g_phys.c.i

g_phys.s: g_phys.c.s
.PHONY : g_phys.s

# target to generate assembly for a file
g_phys.c.s:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/g_phys.c.s
.PHONY : g_phys.c.s

g_reflect.o: g_reflect.c.o
.PHONY : g_reflect.o

# target to build an object file
g_reflect.c.o:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/g_reflect.c.o
.PHONY : g_reflect.c.o

g_reflect.i: g_reflect.c.i
.PHONY : g_reflect.i

# target to preprocess a source file
g_reflect.c.i:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/g_reflect.c.i
.PHONY : g_reflect.c.i

g_reflect.s: g_reflect.c.s
.PHONY : g_reflect.s

# target to generate assembly for a file
g_reflect.c.s:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/g_reflect.c.s
.PHONY : g_reflect.c.s

g_save.o: g_save.c.o
.PHONY : g_save.o

# target to build an object file
g_save.c.o:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/g_save.c.o
.PHONY : g_save.c.o

g_save.i: g_save.c.i
.PHONY : g_save.i

# target to preprocess a source file
g_save.c.i:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/g_save.c.i
.PHONY : g_save.c.i

g_save.s: g_save.c.s
.PHONY : g_save.s

# target to generate assembly for a file
g_save.c.s:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/g_save.c.s
.PHONY : g_save.c.s

g_spawn.o: g_spawn.c.o
.PHONY : g_spawn.o

# target to build an object file
g_spawn.c.o:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/g_spawn.c.o
.PHONY : g_spawn.c.o

g_spawn.i: g_spawn.c.i
.PHONY : g_spawn.i

# target to preprocess a source file
g_spawn.c.i:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/g_spawn.c.i
.PHONY : g_spawn.c.i

g_spawn.s: g_spawn.c.s
.PHONY : g_spawn.s

# target to generate assembly for a file
g_spawn.c.s:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/g_spawn.c.s
.PHONY : g_spawn.c.s

g_svcmds.o: g_svcmds.c.o
.PHONY : g_svcmds.o

# target to build an object file
g_svcmds.c.o:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/g_svcmds.c.o
.PHONY : g_svcmds.c.o

g_svcmds.i: g_svcmds.c.i
.PHONY : g_svcmds.i

# target to preprocess a source file
g_svcmds.c.i:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/g_svcmds.c.i
.PHONY : g_svcmds.c.i

g_svcmds.s: g_svcmds.c.s
.PHONY : g_svcmds.s

# target to generate assembly for a file
g_svcmds.c.s:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/g_svcmds.c.s
.PHONY : g_svcmds.c.s

g_target.o: g_target.c.o
.PHONY : g_target.o

# target to build an object file
g_target.c.o:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/g_target.c.o
.PHONY : g_target.c.o

g_target.i: g_target.c.i
.PHONY : g_target.i

# target to preprocess a source file
g_target.c.i:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/g_target.c.i
.PHONY : g_target.c.i

g_target.s: g_target.c.s
.PHONY : g_target.s

# target to generate assembly for a file
g_target.c.s:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/g_target.c.s
.PHONY : g_target.c.s

g_thing.o: g_thing.c.o
.PHONY : g_thing.o

# target to build an object file
g_thing.c.o:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/g_thing.c.o
.PHONY : g_thing.c.o

g_thing.i: g_thing.c.i
.PHONY : g_thing.i

# target to preprocess a source file
g_thing.c.i:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/g_thing.c.i
.PHONY : g_thing.c.i

g_thing.s: g_thing.c.s
.PHONY : g_thing.s

# target to generate assembly for a file
g_thing.c.s:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/g_thing.c.s
.PHONY : g_thing.c.s

g_tracktrain.o: g_tracktrain.c.o
.PHONY : g_tracktrain.o

# target to build an object file
g_tracktrain.c.o:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/g_tracktrain.c.o
.PHONY : g_tracktrain.c.o

g_tracktrain.i: g_tracktrain.c.i
.PHONY : g_tracktrain.i

# target to preprocess a source file
g_tracktrain.c.i:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/g_tracktrain.c.i
.PHONY : g_tracktrain.c.i

g_tracktrain.s: g_tracktrain.c.s
.PHONY : g_tracktrain.s

# target to generate assembly for a file
g_tracktrain.c.s:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/g_tracktrain.c.s
.PHONY : g_tracktrain.c.s

g_trigger.o: g_trigger.c.o
.PHONY : g_trigger.o

# target to build an object file
g_trigger.c.o:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/g_trigger.c.o
.PHONY : g_trigger.c.o

g_trigger.i: g_trigger.c.i
.PHONY : g_trigger.i

# target to preprocess a source file
g_trigger.c.i:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/g_trigger.c.i
.PHONY : g_trigger.c.i

g_trigger.s: g_trigger.c.s
.PHONY : g_trigger.s

# target to generate assembly for a file
g_trigger.c.s:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/g_trigger.c.s
.PHONY : g_trigger.c.s

g_turret.o: g_turret.c.o
.PHONY : g_turret.o

# target to build an object file
g_turret.c.o:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/g_turret.c.o
.PHONY : g_turret.c.o

g_turret.i: g_turret.c.i
.PHONY : g_turret.i

# target to preprocess a source file
g_turret.c.i:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/g_turret.c.i
.PHONY : g_turret.c.i

g_turret.s: g_turret.c.s
.PHONY : g_turret.s

# target to generate assembly for a file
g_turret.c.s:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/g_turret.c.s
.PHONY : g_turret.c.s

g_utils.o: g_utils.c.o
.PHONY : g_utils.o

# target to build an object file
g_utils.c.o:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/g_utils.c.o
.PHONY : g_utils.c.o

g_utils.i: g_utils.c.i
.PHONY : g_utils.i

# target to preprocess a source file
g_utils.c.i:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/g_utils.c.i
.PHONY : g_utils.c.i

g_utils.s: g_utils.c.s
.PHONY : g_utils.s

# target to generate assembly for a file
g_utils.c.s:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/g_utils.c.s
.PHONY : g_utils.c.s

g_vehicle.o: g_vehicle.c.o
.PHONY : g_vehicle.o

# target to build an object file
g_vehicle.c.o:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/g_vehicle.c.o
.PHONY : g_vehicle.c.o

g_vehicle.i: g_vehicle.c.i
.PHONY : g_vehicle.i

# target to preprocess a source file
g_vehicle.c.i:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/g_vehicle.c.i
.PHONY : g_vehicle.c.i

g_vehicle.s: g_vehicle.c.s
.PHONY : g_vehicle.s

# target to generate assembly for a file
g_vehicle.c.s:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/g_vehicle.c.s
.PHONY : g_vehicle.c.s

g_weapon.o: g_weapon.c.o
.PHONY : g_weapon.o

# target to build an object file
g_weapon.c.o:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/g_weapon.c.o
.PHONY : g_weapon.c.o

g_weapon.i: g_weapon.c.i
.PHONY : g_weapon.i

# target to preprocess a source file
g_weapon.c.i:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/g_weapon.c.i
.PHONY : g_weapon.c.i

g_weapon.s: g_weapon.c.s
.PHONY : g_weapon.s

# target to generate assembly for a file
g_weapon.c.s:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/g_weapon.c.s
.PHONY : g_weapon.c.s

km_cvar.o: km_cvar.c.o
.PHONY : km_cvar.o

# target to build an object file
km_cvar.c.o:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/km_cvar.c.o
.PHONY : km_cvar.c.o

km_cvar.i: km_cvar.c.i
.PHONY : km_cvar.i

# target to preprocess a source file
km_cvar.c.i:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/km_cvar.c.i
.PHONY : km_cvar.c.i

km_cvar.s: km_cvar.c.s
.PHONY : km_cvar.s

# target to generate assembly for a file
km_cvar.c.s:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/km_cvar.c.s
.PHONY : km_cvar.c.s

monster/m_actor.o: monster/m_actor.c.o
.PHONY : monster/m_actor.o

# target to build an object file
monster/m_actor.c.o:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/monster/m_actor.c.o
.PHONY : monster/m_actor.c.o

monster/m_actor.i: monster/m_actor.c.i
.PHONY : monster/m_actor.i

# target to preprocess a source file
monster/m_actor.c.i:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/monster/m_actor.c.i
.PHONY : monster/m_actor.c.i

monster/m_actor.s: monster/m_actor.c.s
.PHONY : monster/m_actor.s

# target to generate assembly for a file
monster/m_actor.c.s:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/monster/m_actor.c.s
.PHONY : monster/m_actor.c.s

monster/m_actor_weap.o: monster/m_actor_weap.c.o
.PHONY : monster/m_actor_weap.o

# target to build an object file
monster/m_actor_weap.c.o:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/monster/m_actor_weap.c.o
.PHONY : monster/m_actor_weap.c.o

monster/m_actor_weap.i: monster/m_actor_weap.c.i
.PHONY : monster/m_actor_weap.i

# target to preprocess a source file
monster/m_actor_weap.c.i:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/monster/m_actor_weap.c.i
.PHONY : monster/m_actor_weap.c.i

monster/m_actor_weap.s: monster/m_actor_weap.c.s
.PHONY : monster/m_actor_weap.s

# target to generate assembly for a file
monster/m_actor_weap.c.s:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/monster/m_actor_weap.c.s
.PHONY : monster/m_actor_weap.c.s

monster/m_berserk.o: monster/m_berserk.c.o
.PHONY : monster/m_berserk.o

# target to build an object file
monster/m_berserk.c.o:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/monster/m_berserk.c.o
.PHONY : monster/m_berserk.c.o

monster/m_berserk.i: monster/m_berserk.c.i
.PHONY : monster/m_berserk.i

# target to preprocess a source file
monster/m_berserk.c.i:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/monster/m_berserk.c.i
.PHONY : monster/m_berserk.c.i

monster/m_berserk.s: monster/m_berserk.c.s
.PHONY : monster/m_berserk.s

# target to generate assembly for a file
monster/m_berserk.c.s:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/monster/m_berserk.c.s
.PHONY : monster/m_berserk.c.s

monster/m_boss2.o: monster/m_boss2.c.o
.PHONY : monster/m_boss2.o

# target to build an object file
monster/m_boss2.c.o:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/monster/m_boss2.c.o
.PHONY : monster/m_boss2.c.o

monster/m_boss2.i: monster/m_boss2.c.i
.PHONY : monster/m_boss2.i

# target to preprocess a source file
monster/m_boss2.c.i:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/monster/m_boss2.c.i
.PHONY : monster/m_boss2.c.i

monster/m_boss2.s: monster/m_boss2.c.s
.PHONY : monster/m_boss2.s

# target to generate assembly for a file
monster/m_boss2.c.s:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/monster/m_boss2.c.s
.PHONY : monster/m_boss2.c.s

monster/m_boss3.o: monster/m_boss3.c.o
.PHONY : monster/m_boss3.o

# target to build an object file
monster/m_boss3.c.o:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/monster/m_boss3.c.o
.PHONY : monster/m_boss3.c.o

monster/m_boss3.i: monster/m_boss3.c.i
.PHONY : monster/m_boss3.i

# target to preprocess a source file
monster/m_boss3.c.i:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/monster/m_boss3.c.i
.PHONY : monster/m_boss3.c.i

monster/m_boss3.s: monster/m_boss3.c.s
.PHONY : monster/m_boss3.s

# target to generate assembly for a file
monster/m_boss3.c.s:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/monster/m_boss3.c.s
.PHONY : monster/m_boss3.c.s

monster/m_boss31.o: monster/m_boss31.c.o
.PHONY : monster/m_boss31.o

# target to build an object file
monster/m_boss31.c.o:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/monster/m_boss31.c.o
.PHONY : monster/m_boss31.c.o

monster/m_boss31.i: monster/m_boss31.c.i
.PHONY : monster/m_boss31.i

# target to preprocess a source file
monster/m_boss31.c.i:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/monster/m_boss31.c.i
.PHONY : monster/m_boss31.c.i

monster/m_boss31.s: monster/m_boss31.c.s
.PHONY : monster/m_boss31.s

# target to generate assembly for a file
monster/m_boss31.c.s:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/monster/m_boss31.c.s
.PHONY : monster/m_boss31.c.s

monster/m_boss32.o: monster/m_boss32.c.o
.PHONY : monster/m_boss32.o

# target to build an object file
monster/m_boss32.c.o:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/monster/m_boss32.c.o
.PHONY : monster/m_boss32.c.o

monster/m_boss32.i: monster/m_boss32.c.i
.PHONY : monster/m_boss32.i

# target to preprocess a source file
monster/m_boss32.c.i:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/monster/m_boss32.c.i
.PHONY : monster/m_boss32.c.i

monster/m_boss32.s: monster/m_boss32.c.s
.PHONY : monster/m_boss32.s

# target to generate assembly for a file
monster/m_boss32.c.s:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/monster/m_boss32.c.s
.PHONY : monster/m_boss32.c.s

monster/m_brain.o: monster/m_brain.c.o
.PHONY : monster/m_brain.o

# target to build an object file
monster/m_brain.c.o:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/monster/m_brain.c.o
.PHONY : monster/m_brain.c.o

monster/m_brain.i: monster/m_brain.c.i
.PHONY : monster/m_brain.i

# target to preprocess a source file
monster/m_brain.c.i:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/monster/m_brain.c.i
.PHONY : monster/m_brain.c.i

monster/m_brain.s: monster/m_brain.c.s
.PHONY : monster/m_brain.s

# target to generate assembly for a file
monster/m_brain.c.s:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/monster/m_brain.c.s
.PHONY : monster/m_brain.c.s

monster/m_chick.o: monster/m_chick.c.o
.PHONY : monster/m_chick.o

# target to build an object file
monster/m_chick.c.o:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/monster/m_chick.c.o
.PHONY : monster/m_chick.c.o

monster/m_chick.i: monster/m_chick.c.i
.PHONY : monster/m_chick.i

# target to preprocess a source file
monster/m_chick.c.i:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/monster/m_chick.c.i
.PHONY : monster/m_chick.c.i

monster/m_chick.s: monster/m_chick.c.s
.PHONY : monster/m_chick.s

# target to generate assembly for a file
monster/m_chick.c.s:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/monster/m_chick.c.s
.PHONY : monster/m_chick.c.s

monster/m_flipper.o: monster/m_flipper.c.o
.PHONY : monster/m_flipper.o

# target to build an object file
monster/m_flipper.c.o:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/monster/m_flipper.c.o
.PHONY : monster/m_flipper.c.o

monster/m_flipper.i: monster/m_flipper.c.i
.PHONY : monster/m_flipper.i

# target to preprocess a source file
monster/m_flipper.c.i:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/monster/m_flipper.c.i
.PHONY : monster/m_flipper.c.i

monster/m_flipper.s: monster/m_flipper.c.s
.PHONY : monster/m_flipper.s

# target to generate assembly for a file
monster/m_flipper.c.s:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/monster/m_flipper.c.s
.PHONY : monster/m_flipper.c.s

monster/m_float.o: monster/m_float.c.o
.PHONY : monster/m_float.o

# target to build an object file
monster/m_float.c.o:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/monster/m_float.c.o
.PHONY : monster/m_float.c.o

monster/m_float.i: monster/m_float.c.i
.PHONY : monster/m_float.i

# target to preprocess a source file
monster/m_float.c.i:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/monster/m_float.c.i
.PHONY : monster/m_float.c.i

monster/m_float.s: monster/m_float.c.s
.PHONY : monster/m_float.s

# target to generate assembly for a file
monster/m_float.c.s:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/monster/m_float.c.s
.PHONY : monster/m_float.c.s

monster/m_flyer.o: monster/m_flyer.c.o
.PHONY : monster/m_flyer.o

# target to build an object file
monster/m_flyer.c.o:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/monster/m_flyer.c.o
.PHONY : monster/m_flyer.c.o

monster/m_flyer.i: monster/m_flyer.c.i
.PHONY : monster/m_flyer.i

# target to preprocess a source file
monster/m_flyer.c.i:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/monster/m_flyer.c.i
.PHONY : monster/m_flyer.c.i

monster/m_flyer.s: monster/m_flyer.c.s
.PHONY : monster/m_flyer.s

# target to generate assembly for a file
monster/m_flyer.c.s:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/monster/m_flyer.c.s
.PHONY : monster/m_flyer.c.s

monster/m_gladiator.o: monster/m_gladiator.c.o
.PHONY : monster/m_gladiator.o

# target to build an object file
monster/m_gladiator.c.o:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/monster/m_gladiator.c.o
.PHONY : monster/m_gladiator.c.o

monster/m_gladiator.i: monster/m_gladiator.c.i
.PHONY : monster/m_gladiator.i

# target to preprocess a source file
monster/m_gladiator.c.i:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/monster/m_gladiator.c.i
.PHONY : monster/m_gladiator.c.i

monster/m_gladiator.s: monster/m_gladiator.c.s
.PHONY : monster/m_gladiator.s

# target to generate assembly for a file
monster/m_gladiator.c.s:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/monster/m_gladiator.c.s
.PHONY : monster/m_gladiator.c.s

monster/m_gunner.o: monster/m_gunner.c.o
.PHONY : monster/m_gunner.o

# target to build an object file
monster/m_gunner.c.o:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/monster/m_gunner.c.o
.PHONY : monster/m_gunner.c.o

monster/m_gunner.i: monster/m_gunner.c.i
.PHONY : monster/m_gunner.i

# target to preprocess a source file
monster/m_gunner.c.i:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/monster/m_gunner.c.i
.PHONY : monster/m_gunner.c.i

monster/m_gunner.s: monster/m_gunner.c.s
.PHONY : monster/m_gunner.s

# target to generate assembly for a file
monster/m_gunner.c.s:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/monster/m_gunner.c.s
.PHONY : monster/m_gunner.c.s

monster/m_hover.o: monster/m_hover.c.o
.PHONY : monster/m_hover.o

# target to build an object file
monster/m_hover.c.o:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/monster/m_hover.c.o
.PHONY : monster/m_hover.c.o

monster/m_hover.i: monster/m_hover.c.i
.PHONY : monster/m_hover.i

# target to preprocess a source file
monster/m_hover.c.i:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/monster/m_hover.c.i
.PHONY : monster/m_hover.c.i

monster/m_hover.s: monster/m_hover.c.s
.PHONY : monster/m_hover.s

# target to generate assembly for a file
monster/m_hover.c.s:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/monster/m_hover.c.s
.PHONY : monster/m_hover.c.s

monster/m_infantry.o: monster/m_infantry.c.o
.PHONY : monster/m_infantry.o

# target to build an object file
monster/m_infantry.c.o:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/monster/m_infantry.c.o
.PHONY : monster/m_infantry.c.o

monster/m_infantry.i: monster/m_infantry.c.i
.PHONY : monster/m_infantry.i

# target to preprocess a source file
monster/m_infantry.c.i:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/monster/m_infantry.c.i
.PHONY : monster/m_infantry.c.i

monster/m_infantry.s: monster/m_infantry.c.s
.PHONY : monster/m_infantry.s

# target to generate assembly for a file
monster/m_infantry.c.s:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/monster/m_infantry.c.s
.PHONY : monster/m_infantry.c.s

monster/m_insane.o: monster/m_insane.c.o
.PHONY : monster/m_insane.o

# target to build an object file
monster/m_insane.c.o:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/monster/m_insane.c.o
.PHONY : monster/m_insane.c.o

monster/m_insane.i: monster/m_insane.c.i
.PHONY : monster/m_insane.i

# target to preprocess a source file
monster/m_insane.c.i:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/monster/m_insane.c.i
.PHONY : monster/m_insane.c.i

monster/m_insane.s: monster/m_insane.c.s
.PHONY : monster/m_insane.s

# target to generate assembly for a file
monster/m_insane.c.s:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/monster/m_insane.c.s
.PHONY : monster/m_insane.c.s

monster/m_medic.o: monster/m_medic.c.o
.PHONY : monster/m_medic.o

# target to build an object file
monster/m_medic.c.o:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/monster/m_medic.c.o
.PHONY : monster/m_medic.c.o

monster/m_medic.i: monster/m_medic.c.i
.PHONY : monster/m_medic.i

# target to preprocess a source file
monster/m_medic.c.i:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/monster/m_medic.c.i
.PHONY : monster/m_medic.c.i

monster/m_medic.s: monster/m_medic.c.s
.PHONY : monster/m_medic.s

# target to generate assembly for a file
monster/m_medic.c.s:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/monster/m_medic.c.s
.PHONY : monster/m_medic.c.s

monster/m_move.o: monster/m_move.c.o
.PHONY : monster/m_move.o

# target to build an object file
monster/m_move.c.o:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/monster/m_move.c.o
.PHONY : monster/m_move.c.o

monster/m_move.i: monster/m_move.c.i
.PHONY : monster/m_move.i

# target to preprocess a source file
monster/m_move.c.i:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/monster/m_move.c.i
.PHONY : monster/m_move.c.i

monster/m_move.s: monster/m_move.c.s
.PHONY : monster/m_move.s

# target to generate assembly for a file
monster/m_move.c.s:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/monster/m_move.c.s
.PHONY : monster/m_move.c.s

monster/m_mutant.o: monster/m_mutant.c.o
.PHONY : monster/m_mutant.o

# target to build an object file
monster/m_mutant.c.o:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/monster/m_mutant.c.o
.PHONY : monster/m_mutant.c.o

monster/m_mutant.i: monster/m_mutant.c.i
.PHONY : monster/m_mutant.i

# target to preprocess a source file
monster/m_mutant.c.i:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/monster/m_mutant.c.i
.PHONY : monster/m_mutant.c.i

monster/m_mutant.s: monster/m_mutant.c.s
.PHONY : monster/m_mutant.s

# target to generate assembly for a file
monster/m_mutant.c.s:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/monster/m_mutant.c.s
.PHONY : monster/m_mutant.c.s

monster/m_parasite.o: monster/m_parasite.c.o
.PHONY : monster/m_parasite.o

# target to build an object file
monster/m_parasite.c.o:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/monster/m_parasite.c.o
.PHONY : monster/m_parasite.c.o

monster/m_parasite.i: monster/m_parasite.c.i
.PHONY : monster/m_parasite.i

# target to preprocess a source file
monster/m_parasite.c.i:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/monster/m_parasite.c.i
.PHONY : monster/m_parasite.c.i

monster/m_parasite.s: monster/m_parasite.c.s
.PHONY : monster/m_parasite.s

# target to generate assembly for a file
monster/m_parasite.c.s:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/monster/m_parasite.c.s
.PHONY : monster/m_parasite.c.s

monster/m_soldier.o: monster/m_soldier.c.o
.PHONY : monster/m_soldier.o

# target to build an object file
monster/m_soldier.c.o:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/monster/m_soldier.c.o
.PHONY : monster/m_soldier.c.o

monster/m_soldier.i: monster/m_soldier.c.i
.PHONY : monster/m_soldier.i

# target to preprocess a source file
monster/m_soldier.c.i:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/monster/m_soldier.c.i
.PHONY : monster/m_soldier.c.i

monster/m_soldier.s: monster/m_soldier.c.s
.PHONY : monster/m_soldier.s

# target to generate assembly for a file
monster/m_soldier.c.s:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/monster/m_soldier.c.s
.PHONY : monster/m_soldier.c.s

monster/m_supertank.o: monster/m_supertank.c.o
.PHONY : monster/m_supertank.o

# target to build an object file
monster/m_supertank.c.o:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/monster/m_supertank.c.o
.PHONY : monster/m_supertank.c.o

monster/m_supertank.i: monster/m_supertank.c.i
.PHONY : monster/m_supertank.i

# target to preprocess a source file
monster/m_supertank.c.i:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/monster/m_supertank.c.i
.PHONY : monster/m_supertank.c.i

monster/m_supertank.s: monster/m_supertank.c.s
.PHONY : monster/m_supertank.s

# target to generate assembly for a file
monster/m_supertank.c.s:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/monster/m_supertank.c.s
.PHONY : monster/m_supertank.c.s

monster/m_tank.o: monster/m_tank.c.o
.PHONY : monster/m_tank.o

# target to build an object file
monster/m_tank.c.o:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/monster/m_tank.c.o
.PHONY : monster/m_tank.c.o

monster/m_tank.i: monster/m_tank.c.i
.PHONY : monster/m_tank.i

# target to preprocess a source file
monster/m_tank.c.i:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/monster/m_tank.c.i
.PHONY : monster/m_tank.c.i

monster/m_tank.s: monster/m_tank.c.s
.PHONY : monster/m_tank.s

# target to generate assembly for a file
monster/m_tank.c.s:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/monster/m_tank.c.s
.PHONY : monster/m_tank.c.s

player/p_chase.o: player/p_chase.c.o
.PHONY : player/p_chase.o

# target to build an object file
player/p_chase.c.o:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/player/p_chase.c.o
.PHONY : player/p_chase.c.o

player/p_chase.i: player/p_chase.c.i
.PHONY : player/p_chase.i

# target to preprocess a source file
player/p_chase.c.i:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/player/p_chase.c.i
.PHONY : player/p_chase.c.i

player/p_chase.s: player/p_chase.c.s
.PHONY : player/p_chase.s

# target to generate assembly for a file
player/p_chase.c.s:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/player/p_chase.c.s
.PHONY : player/p_chase.c.s

player/p_client.o: player/p_client.c.o
.PHONY : player/p_client.o

# target to build an object file
player/p_client.c.o:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/player/p_client.c.o
.PHONY : player/p_client.c.o

player/p_client.i: player/p_client.c.i
.PHONY : player/p_client.i

# target to preprocess a source file
player/p_client.c.i:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/player/p_client.c.i
.PHONY : player/p_client.c.i

player/p_client.s: player/p_client.c.s
.PHONY : player/p_client.s

# target to generate assembly for a file
player/p_client.c.s:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/player/p_client.c.s
.PHONY : player/p_client.c.s

player/p_hud.o: player/p_hud.c.o
.PHONY : player/p_hud.o

# target to build an object file
player/p_hud.c.o:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/player/p_hud.c.o
.PHONY : player/p_hud.c.o

player/p_hud.i: player/p_hud.c.i
.PHONY : player/p_hud.i

# target to preprocess a source file
player/p_hud.c.i:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/player/p_hud.c.i
.PHONY : player/p_hud.c.i

player/p_hud.s: player/p_hud.c.s
.PHONY : player/p_hud.s

# target to generate assembly for a file
player/p_hud.c.s:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/player/p_hud.c.s
.PHONY : player/p_hud.c.s

player/p_menu.o: player/p_menu.c.o
.PHONY : player/p_menu.o

# target to build an object file
player/p_menu.c.o:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/player/p_menu.c.o
.PHONY : player/p_menu.c.o

player/p_menu.i: player/p_menu.c.i
.PHONY : player/p_menu.i

# target to preprocess a source file
player/p_menu.c.i:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/player/p_menu.c.i
.PHONY : player/p_menu.c.i

player/p_menu.s: player/p_menu.c.s
.PHONY : player/p_menu.s

# target to generate assembly for a file
player/p_menu.c.s:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/player/p_menu.c.s
.PHONY : player/p_menu.c.s

player/p_text.o: player/p_text.c.o
.PHONY : player/p_text.o

# target to build an object file
player/p_text.c.o:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/player/p_text.c.o
.PHONY : player/p_text.c.o

player/p_text.i: player/p_text.c.i
.PHONY : player/p_text.i

# target to preprocess a source file
player/p_text.c.i:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/player/p_text.c.i
.PHONY : player/p_text.c.i

player/p_text.s: player/p_text.c.s
.PHONY : player/p_text.s

# target to generate assembly for a file
player/p_text.c.s:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/player/p_text.c.s
.PHONY : player/p_text.c.s

player/p_trail.o: player/p_trail.c.o
.PHONY : player/p_trail.o

# target to build an object file
player/p_trail.c.o:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/player/p_trail.c.o
.PHONY : player/p_trail.c.o

player/p_trail.i: player/p_trail.c.i
.PHONY : player/p_trail.i

# target to preprocess a source file
player/p_trail.c.i:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/player/p_trail.c.i
.PHONY : player/p_trail.c.i

player/p_trail.s: player/p_trail.c.s
.PHONY : player/p_trail.s

# target to generate assembly for a file
player/p_trail.c.s:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/player/p_trail.c.s
.PHONY : player/p_trail.c.s

player/p_view.o: player/p_view.c.o
.PHONY : player/p_view.o

# target to build an object file
player/p_view.c.o:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/player/p_view.c.o
.PHONY : player/p_view.c.o

player/p_view.i: player/p_view.c.i
.PHONY : player/p_view.i

# target to preprocess a source file
player/p_view.c.i:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/player/p_view.c.i
.PHONY : player/p_view.c.i

player/p_view.s: player/p_view.c.s
.PHONY : player/p_view.s

# target to generate assembly for a file
player/p_view.c.s:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/player/p_view.c.s
.PHONY : player/p_view.c.s

player/p_weapon.o: player/p_weapon.c.o
.PHONY : player/p_weapon.o

# target to build an object file
player/p_weapon.c.o:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/player/p_weapon.c.o
.PHONY : player/p_weapon.c.o

player/p_weapon.i: player/p_weapon.c.i
.PHONY : player/p_weapon.i

# target to preprocess a source file
player/p_weapon.c.i:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/player/p_weapon.c.i
.PHONY : player/p_weapon.c.i

player/p_weapon.s: player/p_weapon.c.s
.PHONY : player/p_weapon.s

# target to generate assembly for a file
player/p_weapon.c.s:
	cd /Users/dghost/quake2vr && $(MAKE) -f game/CMakeFiles/vrgamex86.dir/build.make game/CMakeFiles/vrgamex86.dir/player/p_weapon.c.s
.PHONY : player/p_weapon.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... vrgamex86"
	@echo "... __/qcommon/shared/m_flash.o"
	@echo "... __/qcommon/shared/m_flash.i"
	@echo "... __/qcommon/shared/m_flash.s"
	@echo "... __/qcommon/shared/q_shared.o"
	@echo "... __/qcommon/shared/q_shared.i"
	@echo "... __/qcommon/shared/q_shared.s"
	@echo "... acesrc/acebot_ai.o"
	@echo "... acesrc/acebot_ai.i"
	@echo "... acesrc/acebot_ai.s"
	@echo "... acesrc/acebot_cmds.o"
	@echo "... acesrc/acebot_cmds.i"
	@echo "... acesrc/acebot_cmds.s"
	@echo "... acesrc/acebot_compress.o"
	@echo "... acesrc/acebot_compress.i"
	@echo "... acesrc/acebot_compress.s"
	@echo "... acesrc/acebot_items.o"
	@echo "... acesrc/acebot_items.i"
	@echo "... acesrc/acebot_items.s"
	@echo "... acesrc/acebot_movement.o"
	@echo "... acesrc/acebot_movement.i"
	@echo "... acesrc/acebot_movement.s"
	@echo "... acesrc/acebot_nodes.o"
	@echo "... acesrc/acebot_nodes.i"
	@echo "... acesrc/acebot_nodes.s"
	@echo "... acesrc/acebot_spawn.o"
	@echo "... acesrc/acebot_spawn.i"
	@echo "... acesrc/acebot_spawn.s"
	@echo "... g_ai.o"
	@echo "... g_ai.i"
	@echo "... g_ai.s"
	@echo "... g_camera.o"
	@echo "... g_camera.i"
	@echo "... g_camera.s"
	@echo "... g_chase.o"
	@echo "... g_chase.i"
	@echo "... g_chase.s"
	@echo "... g_cmds.o"
	@echo "... g_cmds.i"
	@echo "... g_cmds.s"
	@echo "... g_combat.o"
	@echo "... g_combat.i"
	@echo "... g_combat.s"
	@echo "... g_crane.o"
	@echo "... g_crane.i"
	@echo "... g_crane.s"
	@echo "... g_ctf.o"
	@echo "... g_ctf.i"
	@echo "... g_ctf.s"
	@echo "... g_fog.o"
	@echo "... g_fog.i"
	@echo "... g_fog.s"
	@echo "... g_func.o"
	@echo "... g_func.i"
	@echo "... g_func.s"
	@echo "... g_items.o"
	@echo "... g_items.i"
	@echo "... g_items.s"
	@echo "... g_jetpack.o"
	@echo "... g_jetpack.i"
	@echo "... g_jetpack.s"
	@echo "... g_lights.o"
	@echo "... g_lights.i"
	@echo "... g_lights.s"
	@echo "... g_lock.o"
	@echo "... g_lock.i"
	@echo "... g_lock.s"
	@echo "... g_main.o"
	@echo "... g_main.i"
	@echo "... g_main.s"
	@echo "... g_misc.o"
	@echo "... g_misc.i"
	@echo "... g_misc.s"
	@echo "... g_model.o"
	@echo "... g_model.i"
	@echo "... g_model.s"
	@echo "... g_monster.o"
	@echo "... g_monster.i"
	@echo "... g_monster.s"
	@echo "... g_moreai.o"
	@echo "... g_moreai.i"
	@echo "... g_moreai.s"
	@echo "... g_mtrain.o"
	@echo "... g_mtrain.i"
	@echo "... g_mtrain.s"
	@echo "... g_patchplayermodels.o"
	@echo "... g_patchplayermodels.i"
	@echo "... g_patchplayermodels.s"
	@echo "... g_pendulum.o"
	@echo "... g_pendulum.i"
	@echo "... g_pendulum.s"
	@echo "... g_phys.o"
	@echo "... g_phys.i"
	@echo "... g_phys.s"
	@echo "... g_reflect.o"
	@echo "... g_reflect.i"
	@echo "... g_reflect.s"
	@echo "... g_save.o"
	@echo "... g_save.i"
	@echo "... g_save.s"
	@echo "... g_spawn.o"
	@echo "... g_spawn.i"
	@echo "... g_spawn.s"
	@echo "... g_svcmds.o"
	@echo "... g_svcmds.i"
	@echo "... g_svcmds.s"
	@echo "... g_target.o"
	@echo "... g_target.i"
	@echo "... g_target.s"
	@echo "... g_thing.o"
	@echo "... g_thing.i"
	@echo "... g_thing.s"
	@echo "... g_tracktrain.o"
	@echo "... g_tracktrain.i"
	@echo "... g_tracktrain.s"
	@echo "... g_trigger.o"
	@echo "... g_trigger.i"
	@echo "... g_trigger.s"
	@echo "... g_turret.o"
	@echo "... g_turret.i"
	@echo "... g_turret.s"
	@echo "... g_utils.o"
	@echo "... g_utils.i"
	@echo "... g_utils.s"
	@echo "... g_vehicle.o"
	@echo "... g_vehicle.i"
	@echo "... g_vehicle.s"
	@echo "... g_weapon.o"
	@echo "... g_weapon.i"
	@echo "... g_weapon.s"
	@echo "... km_cvar.o"
	@echo "... km_cvar.i"
	@echo "... km_cvar.s"
	@echo "... monster/m_actor.o"
	@echo "... monster/m_actor.i"
	@echo "... monster/m_actor.s"
	@echo "... monster/m_actor_weap.o"
	@echo "... monster/m_actor_weap.i"
	@echo "... monster/m_actor_weap.s"
	@echo "... monster/m_berserk.o"
	@echo "... monster/m_berserk.i"
	@echo "... monster/m_berserk.s"
	@echo "... monster/m_boss2.o"
	@echo "... monster/m_boss2.i"
	@echo "... monster/m_boss2.s"
	@echo "... monster/m_boss3.o"
	@echo "... monster/m_boss3.i"
	@echo "... monster/m_boss3.s"
	@echo "... monster/m_boss31.o"
	@echo "... monster/m_boss31.i"
	@echo "... monster/m_boss31.s"
	@echo "... monster/m_boss32.o"
	@echo "... monster/m_boss32.i"
	@echo "... monster/m_boss32.s"
	@echo "... monster/m_brain.o"
	@echo "... monster/m_brain.i"
	@echo "... monster/m_brain.s"
	@echo "... monster/m_chick.o"
	@echo "... monster/m_chick.i"
	@echo "... monster/m_chick.s"
	@echo "... monster/m_flipper.o"
	@echo "... monster/m_flipper.i"
	@echo "... monster/m_flipper.s"
	@echo "... monster/m_float.o"
	@echo "... monster/m_float.i"
	@echo "... monster/m_float.s"
	@echo "... monster/m_flyer.o"
	@echo "... monster/m_flyer.i"
	@echo "... monster/m_flyer.s"
	@echo "... monster/m_gladiator.o"
	@echo "... monster/m_gladiator.i"
	@echo "... monster/m_gladiator.s"
	@echo "... monster/m_gunner.o"
	@echo "... monster/m_gunner.i"
	@echo "... monster/m_gunner.s"
	@echo "... monster/m_hover.o"
	@echo "... monster/m_hover.i"
	@echo "... monster/m_hover.s"
	@echo "... monster/m_infantry.o"
	@echo "... monster/m_infantry.i"
	@echo "... monster/m_infantry.s"
	@echo "... monster/m_insane.o"
	@echo "... monster/m_insane.i"
	@echo "... monster/m_insane.s"
	@echo "... monster/m_medic.o"
	@echo "... monster/m_medic.i"
	@echo "... monster/m_medic.s"
	@echo "... monster/m_move.o"
	@echo "... monster/m_move.i"
	@echo "... monster/m_move.s"
	@echo "... monster/m_mutant.o"
	@echo "... monster/m_mutant.i"
	@echo "... monster/m_mutant.s"
	@echo "... monster/m_parasite.o"
	@echo "... monster/m_parasite.i"
	@echo "... monster/m_parasite.s"
	@echo "... monster/m_soldier.o"
	@echo "... monster/m_soldier.i"
	@echo "... monster/m_soldier.s"
	@echo "... monster/m_supertank.o"
	@echo "... monster/m_supertank.i"
	@echo "... monster/m_supertank.s"
	@echo "... monster/m_tank.o"
	@echo "... monster/m_tank.i"
	@echo "... monster/m_tank.s"
	@echo "... player/p_chase.o"
	@echo "... player/p_chase.i"
	@echo "... player/p_chase.s"
	@echo "... player/p_client.o"
	@echo "... player/p_client.i"
	@echo "... player/p_client.s"
	@echo "... player/p_hud.o"
	@echo "... player/p_hud.i"
	@echo "... player/p_hud.s"
	@echo "... player/p_menu.o"
	@echo "... player/p_menu.i"
	@echo "... player/p_menu.s"
	@echo "... player/p_text.o"
	@echo "... player/p_text.i"
	@echo "... player/p_text.s"
	@echo "... player/p_trail.o"
	@echo "... player/p_trail.i"
	@echo "... player/p_trail.s"
	@echo "... player/p_view.o"
	@echo "... player/p_view.i"
	@echo "... player/p_view.s"
	@echo "... player/p_weapon.o"
	@echo "... player/p_weapon.i"
	@echo "... player/p_weapon.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /Users/dghost/quake2vr && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

